openapi: 3.0.1
info:
  title: Echo1
  description: ''
  version: '1.0'
servers:
  - url: https://az-apim-demo-dev-consumption01.azure-api.net/echo1
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]