apimServiceName: az-apim-demo-prod-consumption01
backends:
  - name: az-func-poc
    properties:
      url: "https://az-func-poc-002.azurewebsites.net/api"
      resourceid: "https://management.azure.com/subscriptions/08e60e02-848b-479e-a6c2-b88a7dfc5a63/resourceGroups/az-func-poc-rg/providers/Microsoft.Web/sites/az-func-poc-002"
